### PR TITLE
Implemented import for BGS HYBNAT result files (*.wel, *.bcs)

### PR DESCRIPTION
**Pull request by TobiasRosskopf**
Implemented new file imports for WEL files and BCS files corresponding to HYBNAT (BGS Wasser GmbH). These series include a relative timestamp like HydroAS. So it uses the same reference date picker. The former `HYDRO_AS-2D_diag` is now renamed to `ReferenceDatePickerDialog` cause of its use in multiple file format imports.

### CODE REVIEW

**Comment by jamaa** [comment]
Nice! Can you please add some example files to the [Datasets repo](https://github.com/bluemodel/BlueM.Datasets), in a new subfolder `Wave\HYBNAT`, and also add some information to the wiki here https://wiki.bluemodel.org/index.php/HYBNAT_result_files ?

**Comment by TobiasRosskopf** [comment]
Yes, I already added some sample files to my local repository of [BlueM.Datasets](https://github.com/bluemodel/BlueM.Datasets) but I want to anonymize it before pushing it on GitHub. I also would make an entry to the wiki but I don't think I have an account yet.

**Comment by TobiasRosskopf** [comment]
I created a [pull request](https://github.com/bluemodel/BlueM.Datasets/pull/2) in [BlueM.Datasets](https://github.com/bluemodel/BlueM.Datasets) with some example files of HYBNAT.

**Comment by TobiasRosskopf** [comment]
While collecting the example files I recognized some differences in the WEL format. The line number where the data starts depends not only on the element type, but also on the calculation method and optional info tags. So I have to rewrite some of my code before merging to master!

**Comment by jamaa** [comment]
>So I have to rewrite some of my code before merging to master!

alright, no problem. That's why we always need examples :-) Even better would be unit tests but I haven't gotten around to adding tests for reading file formats

**Review by jamaa — APPROVED** [review]

**Comment by jamaa** [comment]
Thanks for the contribution @TobiasRosskopf ! Feel free to also add some information to the wiki page https://wiki.bluemodel.org/index.php/HYBNAT_result_files (or post it here and I can add it to the wiki)

**Pull request merged**
