### PR TITLE
SWMM

### LINKED ISSUE #63: 736: Series names of SWMM OUT files are not always unique
| | |
| --- | --- |
| Original bug ID | 736 |
| Reported by | froehlich on 2020-05-25 |
| Affects version | 1.8 |
| Component | Import |
| Severity | normal |
| Priority | P3 |
| Milestone | --- |
| Assigned to | heusch |
| Status | NEW  |

**Comments:**

froehlich on 2020-05-25:

> For example, when importing the file A128.out from the Datasets repository, the import dialog shows two series with the identical name S101 Depth. These series should have different names in order to be able to distinguish them. Because of #62, selecting both series for import currently also causes an error.
> 
> The series names are constructed in SWMM_OUT.readSeriesInfo() and then used again in SWMM_OUT.readFile() in order to determine whether a series has been selected for import. Either the naming has to be changed in both of these places, or, changed in only readSeriesInfo and then use a different identifying mechanism in readFile (probably better anyway).

### PR DESCRIPTION
**Pull request by jamaa**
Improvements for SWMM file formats

fixes #63 among other things

### CODE REVIEW

**Comment by jamaa** [comment]
I have fixed #63 and while I was at it fixed some other issues regarding units. 

I noticed the unit notation is currently slightly different to what we usually get from other timeseries formats, e.g. "mm/day" instead of "mm/d", "mm/hr" instead of "mm/h", "MGL" instead of "mg/l" and "LPS" instead of "l/s", etc. (I have already changed the last one actually). I was wondering, is this the "official" notation in SWMM or should we change all of them to what I perceive as usual? Current units see https://github.com/bluemodel/BlueM.Wave/blob/d7968d2676ab8d393741194c7b3c8eaf57acabb9/source/FileFormats/SWMM_OUT.vb#L313

I also wanted to take this opportunity to do some house cleaning: I would really like to get rid of the properties `Timeseries.Objekt` and `Timeseries.Type`. These are only ever assigned when reading SWMM (and Hystem-Extran) files and only ever used when exporting to SWMM interface text format (see https://github.com/bluemodel/BlueM.Wave/blob/swmm/source/FileFormats/SWMM_INTERFACE.vb#L284). Do we want to keep this SWMM interface text format export? If so, I will try to implement a workaround by storing the required information in the timeseries metadata instead.

**Comment by SHeusch** [comment]
> I was wondering, is this the "official" notation in SWMM or should we change all of them to what I perceive as usual?

Yes, "LPS, MGL ..." is the "official" notation in SWMM. From a Wave-POV synchronisation to l/s, mg/l is understandable.  For a SWMM-user it would be more natural to stick with the SWMM-notation. My opinion: We should stick to the option which makes the code slimmer or easier to understand.

**Comment by SHeusch** [comment]
> I also wanted to take this opportunity to do some house cleaning: I would really like to get rid of the properties `Timeseries.Objekt` and `Timeseries.Type`. These are only ever assigned when reading SWMM (and Hystem-Extran) files and only ever used when exporting to SWMM interface text format (see https://github.com/bluemodel/BlueM.Wave/blob/swmm/source/FileFormats/SWMM_INTERFACE.vb#L284). Do we want to keep this SWMM interface text format export? If so, I will try to implement a workaround by storing the required information in the timeseries metadata instead.

The interface file is good if you calculate external discharges or flows and use them as inflow for a SWMM model. Therefore I would plead to stick with that file format.

**Comment by jamaa** [comment]
> > I was wondering, is this the "official" notation in SWMM or should we change all of them to what I perceive as usual?
> 
> Yes, "LPS, MGL ..." is the "official" notation in SWMM. From a Wave-POV synchronisation to l/s, mg/l is understandable. For a SWMM-user it would be more natural to stick with the SWMM-notation. My opinion: We should stick to the option which makes the code slimmer or easier to understand.

I think we'll stick to the "official" SWMM notation then, will also change m³/s and l/s back to CMS and LPS so that is is uniform

**Comment by jamaa** [comment]
> The interface file is good if you calculate external discharges or flows and use them as inflow for a SWMM model. Therefore I would plead to stick with that file format.

Understood. The export to the SWMM interface format currently requires the `Objekt`and `Type` properties, which are only assigned if a series was read from SWMM or Hystem-Extran. So series from any other source can currently not be exported to SWMM. Moving this information to the series metadata would also allow other series to be exported to SWMM, so it would be a win-win :-)

**Comment by jamaa** [comment]
by the way, units from SWMM binary files are currently handled in Wave but should really be handled by the SWMM.DLLAdapter: https://github.com/bluemodel/SWMM.DLLAdapter/issues/2

**Comment by jamaa** [comment]
I think this is ready. See the changelog for a summary of changes. Would you like to test this before we release it, @SHeusch ? If so, can you checkout and build the `swmm` branch yourself or do you want me to compile a "pre-release"?

**Comment by SHeusch** [comment]
> I think this is ready. See the changelog for a summary of changes. Would you like to test this before we release it, @SHeusch ? If so, can you checkout and build the `swmm` branch yourself or do you want me to compile a "pre-release"?

I cloned the branch in VS2022 but could't compile it due to an error with the TeeChart-License. I tried to follow the advise from here: https://wiki.bluemodel.org/index.php/BlueM.Sim_Development
but I don't have the TChart-license file which I'm supposed to delete.

**Comment by jamaa** [comment]
From the Wave [developer docs](https://bluemodel.github.io/BlueM.Wave/articles/intro.html):
>To use TeeChart Pro trial version, create an empty file `BlueM.Wave\source\My Project\TeeChart.licenses` or remove the corresponding entry from the project in Visual Studio

What is meant by "Removing the entry from the project in Visual Studio" is shown in the screenshot below
grafik

I guess these instructions need to be made clearer. How about we write the following:

* the TeeChart Pro license file is expected to be at `BlueM.Wave\source\My Project\TeeChart.licenses`
* if you don't have a license file, you can use the TeeChart trial version, which will display a watermark in all charts, by doing one of the following:
  * create an empty text file in its place (recommended)
  * or remove the license file from the project by right-clicking it in the Visual Studio Solution Explorer (the "Show all files" button at the top must be activated in order to see it) and then selecting "Exclude from project"

**Comment by SHeusch** [comment]
Thanks, I was able to build it.

**Comment by SHeusch** [comment]
Hmm, I don't see the system information when importing a out-file.

**Comment by jamaa** [comment]
> Hmm, I don't see the system information when importing a out-file.

which out file is this? I tried the two out files we currently have in [BlueM.Datasets](https://github.com/bluemodel/BlueM.Datasets/tree/master/Wave/SWMM) and both are shown with system variables when importing in Wave.

grafik

**Comment by SHeusch** [comment]
Your screenshot looks different. I probably didn't create the right Wave-version than.

**Comment by jamaa** [comment]
just remembered one more thing we could improve: currently time series imported from SWMM files all have the interpretation `Undefined`. Do you happen to know what interpretation SWMM files use, @SHeusch ? See https://wiki.bluemodel.org/index.php/Time_series_management#Interpretation_of_time_series for possible interpretations.

**Comment by SHeusch** [comment]
I believe that SWMM doesn't give any kind of interpretation. It's rhe users task to make sure that the time series is interpreted correctly.

**Comment by jamaa** [comment]
OK, we'll leave the interpretation as undefined then. 

Have you had time to test this branch yet? It would be good if you could test whether a SWMM Interface file exported by Wave can be properly read by SWMM. Everything else I'm pretty confident of it working as expected (hopefully :-)

**Comment by SHeusch** [comment]
It's on my todo-list.  I havent't found time yet. Need to test the out-file as well yet. I need more TIME!

**Comment by jamaa** [comment]
merged this into master before it gets too old, if there are any remaining things to change regarding SWMM files we can always open new issues

**Pull request merged**
